### ISSUE TITLE
Create bugfix release to fix broken gem

### ISSUE THREAD

**Issue by HyperHamster** [kaspernj/pulseaudio#9]
The latest release (v0.0.9) does not include d32bce1099ebb1f36133ee367bfa630b8a4758ec, however it still depends on the latest Wref which causes the issues mentioned in and fixed by #8.

**Comment by HyperHamster** [comment]
@kaspernj I hate to ping you, but the gem is currently and has been broken for some time. I stumbled across this gem initially finding it to be broken but quickly fixed it in my scripts by requiring it like so:
```ruby
gem 'wref', '<= 0.0.6'
gem 'knjrbfw', '<= 0.0.110'
require 'pulseaudio'
```
However, now that you've merged #8 into master, doing this would no longer be necessary if only you were to create a new release.

**Comment by kaspernj** [comment]
@HyperHamster Feel free to ping me if I am being lazy ;-) I have added minimum versions to master and released a new version with those fixes.

Does it work for you?

**Comment by HyperHamster** [comment]
Works beautifully now, no more need to set gem versions. Thank you.
